export const INVENTORY = [{
    id:1,
    part_name:'Airtex Water Block',
    part_type:'Water Pump',
    code:'475861',
    manufacturer:'Hyundai',
    vehicle_type:'Tucson',
    year_s:'2020',
    price:36.00,
    stock_level:12,
    stock_level_threshold:4
},{id:2,
    part_name:'Ford Grill',
    part_type:'Cooling',
    code:'G781-94PQ',
    manufacturer:'Ford',
    vehicle_type:'Fiesta',
    year_s:'2017',
    price:109.99,
    stock_level:6,
    stock_level_threshold:3}];
